CREATE DATABASE IF NOT EXISTS issues;

ALTER DATABASE issues
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON issues.* TO pc@localhost IDENTIFIED BY 'pc';

USE issues;

CREATE TABLE IF NOT EXISTS issues (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  description VARCHAR(4000)
) engine=InnoDB;
